apiVersion: v1
kind: Pod
metadata:           # Metadata: here we can define data about the object we are about to create.
  name: webserver-pod-multi
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: webwatcher
    image: afakharany/watcher:latest