apiVersion: v1
kind: Pod
metadata:           # Metadata: here we can define data about the object we are about to create.
  name: webserver
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80