---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-clusterip-deployment
  labels:
    app: nginx-clusterip-deployment
spec:
  template:
    metadata:
      name: nginx-clusterip-pod
      labels:
        app: nginx-clusterip-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "blue"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In
                values: 
                - large
                - medium  
  replicas: 3
  selector:
    matchLabels:
      app: nginx-clusterip-pod